language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-nginx.gemspec
- gem install sensu-plugins-nginx-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: rubygems
  api_key:
    secure: aYIcQWof/3mOwnJocuJlasvu1i99+UYlhvVjVdlnKTOqzVoWthx0mADPeHZJfr2XOHV+THO7mHtGlc9dQdZ1JSGvMGItShzHp7Y3JLzJHPSy3QSY1A8LmDkF3lMh9UY5Gu6InT4a0gAchz3qv5jjlylFRAl+tTtPXzIhftMjfJs=
  gem: sensu-plugins-nginx
  on:
    tags: true
    repo: sensu-plugins/sensu-plugins-nginx
    all_branches: true
    rvm: 2.3.0
    rvm: 2.4.1
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-nginx
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
